# Generated by Django 4.2.4 on 2024-07-06 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pachamodel', '0002_usuario_expresion_usuario_humext_usuario_humint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='brillo',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
